### PR TITLE
Add a new speaker yweweler

### PR DESCRIPTION
**Pull request by yweweler**
Add a new speaker yweweler

### CODE REVIEW

**Comment by Jakobovski** [comment]
Did you listen to the recordings to make sure they sound ok?

Is the audio clear and trimmed? Ie there is not a lot of empty time in the beginning and end of the recordings?

**Comment by yweweler** [comment]
I listened through all recordings and adjusted the empty time in some files to make them more homogenous. 

Now all of them should be fine.

**Comment by Jakobovski** [comment]
Thanks for your contribution

**Comment by Jakobovski** [comment]
what is the bit depth and number of channels of your recordings? Is it consistent with the other recordings?

**Comment by Jakobovski** [comment]
also you had a typo in metadata.py. I fixed it

**Pull request merged**
